// Generated by CoffeeScript 1.6.3
(function() {
  var editorInit, exampleInit, main, update;

  editorInit = function() {
    var Range, editor, ff, prog, session;
    Range = ace.require("ace/range").Range;
    editor = ace.edit("editor");
    e8vm.editor = editor;
    session = editor.getSession();
    editor.setTheme("ace/theme/tomorrow");
    session.setMode("ace/mode/golang");
    editor.renderer.setShowGutter(false);
    editor.setHighlightActiveLine(false);
    editor.setShowFoldWidgets(false);
    editor.setDisplayIndentGuides(false);
    ff = "Consolas, Inconsolata, Monaco, \"Courier New\", Courier, monospace";
    editor.setOptions({
      maxLines: Infinity,
      minLines: 10,
      fontFamily: ff,
      fontSize: "13px"
    });
    editor.commands.removeCommands(["gotoline", "find"]);
    prog = ['mov r0 r1'].join('\n');
    editor.setValue(prog);
    editor.clearSelection();
  };

  exampleInit = function() {
    var examples, f, li, ul, _i, _len;
    examples = ['3p4'];
    ul = $('<ul id="examples"/>');
    for (_i = 0, _len = examples.length; _i < _len; _i++) {
      f = examples[_i];
      li = $('<li><a href="#">' + f + '</a></li>');
      li.find('a').click(function(e) {
        e.preventDefault();
        $.ajax("tests/" + f + ".x", {
          success: function(dat) {
            e8vm.editor.setValue(dat);
            e8vm.editor.clearSelection();
          }
        });
      });
      ul.append(li);
    }
    $("div#filelist").append(ul);
  };

  update = function() {
    var code, res;
    code = e8vm.editor.getValue();
    res = e8vm.compile("func.s8", code);
    $("#compile").html(res.errs);
    $("#dasm").html(res.dasm);
  };

  main = function() {
    editorInit();
    exampleInit();
    update();
    e8vm.editor.getSession().on("change", function() {
      update();
    });
  };

  $(document).ready(main);

}).call(this);

/*
//@ sourceMappingURL=play.map
*/
